[package]
name = "sonnietechnologyllc/SonnieTech-website"
version = "0.1.0"
description = "Sonnies Technology LLC - Corporate Website"

[dependencies]
"wasmer/node" = "*"

[fs]
"/public" = "public"
"/app" = "." 

[[command]]
name = "start"
module = "wasmer/node:node"
runner = "https://webc.org/runner/wasi"
annotations = { "wasi.env" = ["PORT=8080"] }
args = ["server.js"] 
