[package]
name = "msorsor1956/sonnietech"
version = "0.1.0"
description = "Sonnies Technology LLC - Corporate Website"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "."

[[command]]
name = "start"
module = "wasmer/static-web-server:web-server"
runner = "https://webc.org/runner/wasi"
annotations = { "wasi.env" = ["SERVER_ROOT=/public"] }
